import { NextRequest, NextResponse } from "next/server";
import { requireSession } from "@/lib/auth";
import { ReportService } from "@/lib/services/ReportService";
import PDFDocument from "pdfkit";

export const runtime = "nodejs";

// Server-side PDF generation via pdfkit — a pure Node.js library with no
// headless-browser dependency, so this works identically in any deployment
// environment (including serverless) without relying on browser print hacks.
export async function GET(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  try {
    await requireSession();
  } catch {
    return NextResponse.json({ error: "Sign in required." }, { status: 401 });
  }

  const report = ReportService.latest(id);
  if (!report || !report.snapshot || !("decision" in report.snapshot)) {
    return NextResponse.json({ error: "Generate a report before downloading a PDF." }, { status: 400 });
  }

  const snapshot = report.snapshot as {
    decision: { name: string; category: string; status: string; owner: string };
    requirement: { rawInput: string; budgetMin?: number; budgetMax?: number; currency: string };
    criteria: { name: string; weight: number }[];
    vendorRows: {
      name: string;
      overallScore: number;
      startingPrice: number;
      currency: string;
      explanation: { summary: string; strengths: string[]; weaknesses: string[] };
    }[];
    selectedVendor?: { name: string };
    rationale?: string;
    generatedAt: string;
  };

  const chunks: Buffer[] = [];
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  doc.on("data", (c) => chunks.push(c));

  const done = new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  doc.fontSize(20).fillColor("#14213d").text("MATCHIQ Decision Report", { align: "left" });
  doc.moveDown(0.3);
  doc.fontSize(11).fillColor("#475569").text(`${snapshot.decision.name} · ${snapshot.decision.category}`);
  doc.fontSize(9).fillColor("#94a3b8").text(`Generated ${new Date(snapshot.generatedAt).toLocaleString("en-GB")} · Owner: ${snapshot.decision.owner}`);
  doc.moveDown(1);

  doc.fontSize(13).fillColor("#0f172a").text("Executive summary");
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor("#334155").text(
    snapshot.selectedVendor
      ? `${snapshot.selectedVendor.name} was selected after evaluating ${snapshot.vendorRows.length} vendors against ${snapshot.criteria.length} weighted criteria.`
      : `${snapshot.vendorRows.length} vendors were evaluated against ${snapshot.criteria.length} weighted criteria. A final selection has not yet been made.`
  );
  doc.moveDown(1);

  doc.fontSize(13).fillColor("#0f172a").text("Business requirement");
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor("#334155").text(snapshot.requirement.rawInput, { width: 480 });
  doc.moveDown(1);

  doc.fontSize(13).fillColor("#0f172a").text("Decision criteria & weights");
  doc.moveDown(0.3);
  snapshot.criteria.forEach((c) => {
    doc.fontSize(10).fillColor("#334155").text(`${c.name} — ${c.weight}%`);
  });
  doc.moveDown(1);

  doc.fontSize(13).fillColor("#0f172a").text("Score comparison");
  doc.moveDown(0.3);
  snapshot.vendorRows.forEach((r) => {
    doc.fontSize(10).fillColor("#0f172a").text(`${r.name} — ${r.overallScore}% (from £${r.startingPrice}/mo)`, { continued: false });
  });
  doc.moveDown(1);

  doc.fontSize(13).fillColor("#0f172a").text("Detailed evaluation & trade-offs");
  doc.moveDown(0.3);
  snapshot.vendorRows.forEach((r) => {
    doc.fontSize(11).fillColor("#14213d").text(r.name);
    doc.fontSize(9).fillColor("#475569").text(r.explanation.summary, { width: 480 });
    if (r.explanation.strengths.length) doc.fontSize(9).fillColor("#0f766e").text(`Strengths: ${r.explanation.strengths.join(", ")}`, { width: 480 });
    if (r.explanation.weaknesses.length) doc.fontSize(9).fillColor("#b91c1c").text(`Watch-outs: ${r.explanation.weaknesses.join(", ")}`, { width: 480 });
    doc.moveDown(0.6);
  });

  if (snapshot.selectedVendor) {
    doc.moveDown(0.4);
    doc.fontSize(13).fillColor("#0f172a").text("Final recommendation");
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#334155").text(`Selected vendor: ${snapshot.selectedVendor.name}`);
    if (snapshot.rationale) doc.fontSize(10).fillColor("#334155").text(`Rationale: ${snapshot.rationale}`, { width: 480 });
  }

  doc.moveDown(1.5);
  doc.fontSize(8).fillColor("#94a3b8").text("Generated by MATCHIQ. Vendor catalogue is synthetic demo data — no real vendor partnerships implied.");

  doc.end();
  const buffer = await done;

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="matchiq-decision-report.pdf"`,
    },
  });
}
